public class Address {
    public void homeAddress(){
        string yourName = 'Sahin';
        integer totalFamilyMember = 5;
        string houseNmae = 'My Home';
        integer houseNumber = 7070;
        string streetNmae = 'Dalewood Drive';
        string cityName = 'Missassauga';
        string stateName = 'Ontario';
        string stateISOCode = 'ON';
        string countryName = 'Canada';
        string countryISOCode = 'CAN';
        string zipCode = 'LT44G8';
        boolean isHome = true;
        system.debug(yourName);
        system.debug(totalFamilyMember);
        system.debug(houseNmae);
        system.debug(houseNumber);
        system.debug(streetNmae);
        system.debug(cityName);
        system.debug(stateName);
        system.debug(stateISOCode);
        system.debug(countryName);
        system.debug(countryISOCode);
        system.debug(zipCode);
        system.debug(isHome);
    }
   
}
