@isTest
public  class CalculatorSimpleTest {
    @isTest
    private static void testAdd1(){
        // we can call other methods, which accepts params.
        integer sum = CalculatorSimple.add(10, 15);
        Integer expectedSum = 25;
        System.assertEquals(expectedSum, sum);

    }
    @isTest
    private static void testAdd2(){
        // we can call other methods, which accepts params.
        integer sum = CalculatorSimple.add(10, 15, 10);
        Integer expectedSum = 35;
        System.assertEquals(expectedSum, sum);

    }
}
