// public class DatetimeMethodsDemo {
//     public void calculateAgeInMonths(){
//         date birthdate = date.newInstance(1979, 06, 03);
//         date todayDate = date.today();

//         integer ageInMonth = birthdate.monthsBetween(todayDate);
//         system.debug('My age is-->' + ageInMonth);
//     }

//     public void printSubscriptionEndDate(){
//         date subscriptionStartDate = date.today();
        
//         date subscriptionEndDate = subscriptionStartDate.addDays(1000);
//         system.debug('subscription end date is ...' + subscriptionEndDate);




//     }
  
// }
 