public class DML2Assgn {
 

//     public static void dmlAssgnUpdate(){
//        List<Account> ListAssgn = [select id, name from Account 
//        ORDER BY CreatedDate desc  limit 155];
//        List<Account> updateAcc = new List<Account>();

//        for(Account eachAcc: ListAssgn){
//         eachAcc.Name = eachAcc.Name + 'Mr Aytug is UPDATED';
//         updateAcc.add(eachAcc);
// s
//        }
//        if (!updateAcc.isEmpty()){
//         update updateAcc;
//        }
      
// }
}
