




// Integer x = CalculatorSimple.add(5, 55);
// system.debug(x);

// system.debug('8+45+155 =? ' + CalculatorSimple.add(8, 45, 155));
List<Integer> ListInteger = new List<Integer>();
        ListInteger.add(15);
        ListInteger.add(21);
        ListInteger.add(10);
        ListInteger.add(15);
        ListInteger.add(15); 
        Integer sum =   ListDemoForLoop.add(ListInteger);
        System.debug('Sum of list ' +sum);