decimal a = Calculator .dynamicCalulationMethod(10.2, 15.2, 'Adition');
system.debug(a);
decimal b = Calculator.dynamicCalulationMethod(10.2, 15.2, 'Substraction');
system.debug(b);
decimal c = Calculator.dynamicCalulationMethod(10.2, 15.2, 'Multipication');
system.debug(c);
decimal d = Calculator.dynamicCalulationMethod(10.2, 15.2, 'Divicion');
system.debug(d);
decimal e = Calculator.dynamicCalulationMethod(10.2, 15.2, 'Adition');
system.debug(e);

