// string c2 = ListDemo.candidatesList(2);
// system.debug(c2);

// string c5 = ListDemo.candidatesList(5);
// system.debug(c5);

// string c55 = ListDemo.candidatesList(-5);
// system.debug(c55);


// ListDemo.randomIntegerList();

List<String> test = new List<String>{'Merhaba ', 'iyi dersler'};
String silinenDeger = test.remove(0);
system.debug('silinen deger:' + silinenDeger);
system.debug(test);

